#!/usr/bin/env node
// PreToolUse hook (Edit|Write|MultiEdit|NotebookEdit): refuse edits Claude should not make by hand.
// Exit code 2 blocks the tool call; the message on stderr goes back to Claude.
import { relative, resolve } from 'node:path';

let input = '';
for await (const chunk of process.stdin) input += chunk;
let file = '';
try {
  const data = JSON.parse(input);
  file = data.tool_input?.file_path ?? data.tool_input?.notebook_path ?? '';
} catch {
  process.exit(0); // not our business
}
if (!file) process.exit(0);
const root = process.env.CLAUDE_PROJECT_DIR ?? process.cwd();
const rel = relative(root, resolve(root, file)).split('\\').join('/');

const rules = [
  [/(^|\/)\.env(\.|$)(?!example$)/, 'API keys live in .env: never write them from Claude (edit .env.example for documentation).'],
  [/(^|\/)keys\.json$/, 'keys.json holds API keys: do not edit it.'],
  [/^pnpm-lock\.yaml$/, 'pnpm-lock.yaml is generated: change package.json and run `pnpm install` instead.'],
  [/^workers\/py\/uv\.lock$/, 'uv.lock is generated: change pyproject.toml and run `uv lock` in workers/py instead.'],
  [/^docs\/en\/components\.md$/, 'docs/en/components.md is generated from the component definitions: edit packages/lesson/src/components/*.ts and run `pnpm docs:components`.'],
  [/(^|\/)dist\//, 'dist/ is build output: edit the sources and rebuild.'],
  [/\.warqa\/(cache|dist|qa)\//, 'This is a generated folder of a book (cache, export or QA screenshots): regenerate it instead.'],
  [/^packages\/lesson\/dist\/bundle\/geo-world/, 'Map data is generated by packages/lesson/build.mjs.'],
];
for (const [re, why] of rules)
  if (re.test(rel)) {
    process.stderr.write(`Blocked edit of ${rel}: ${why}\n`);
    process.exit(2);
  }
process.exit(0);
