// Generate docs/en/components.md from the component definitions (run: pnpm docs:components).
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import * as z from 'zod';
import { COMPONENTS, GENERIC_ACTIONS } from '../src/index.ts';

const out = fileURLToPath(new URL('../../../docs/en/components.md', import.meta.url));
const packs: Record<string, string> = {
  core: 'Core',
  stem: 'STEM',
  humanities: 'Humanities',
  document: 'Any document',
  kids: "Children's books",
  custom: 'Experimental (custom code)',
};
const lines: string[] = [
  '# Components',
  '',
  '<!-- generated by packages/lesson/scripts/gen-docs.mts — edit the component definitions in packages/lesson/src/components, not this file -->',
  '',
  'Models build lessons from these components. Each node is `{"id", "type", "slot"?, "enter"?, ...props}`; cues target a node (`"eq1"`) or one of its parts (`"eq1#tok:2"`).',
  '',
  `**Generic actions** (any node or part): ${GENERIC_ACTIONS.map((a) => `\`${a}\``).join(', ')}.`,
  '',
];
for (const [pack, label] of Object.entries(packs)) {
  const defs = Object.values(COMPONENTS).filter((d) => d.pack === pack);
  if (!defs.length) continue;
  lines.push(`## ${label}`, '');
  for (const d of defs) {
    lines.push(
      `### \`${d.type}\``,
      '',
      d.doc,
      '',
      `Default slot: \`${d.defaultSlot}\`. Localized props: ${d.text.length ? d.text.map((t) => `\`${t}\``).join(', ') : 'none'}.`,
      '',
    );
    const js = z.toJSONSchema(d.props, { unrepresentable: 'any', io: 'input' }) as {
      properties?: Record<string, { description?: string; type?: string }>;
      required?: string[];
    };
    lines.push('| prop | required | type |', '| --- | --- | --- |');
    for (const [k, v] of Object.entries(js.properties ?? {}))
      lines.push(
        `| \`${k}\` | ${js.required?.includes(k) ? 'yes' : ''} | ${v.type ?? ('anyOf' in v ? 'union' : 'object')} |`,
      );
    lines.push('');
    for (const [name, a] of Object.entries(d.actions ?? {}))
      lines.push(
        `- **action \`${name}\`** — ${a.doc} Args: \`${JSON.stringify(z.toJSONSchema(a.args, { unrepresentable: 'any', io: 'input' }).properties ?? {})}\``,
      );
    if (d.actions) lines.push('');
    for (const ex of d.examples.slice(0, 1)) {
      lines.push('Example:', '', '```json', JSON.stringify({ id: 'x', type: d.type, ...ex.props }, null, 1), '```', '');
      if (ex.cues?.length) lines.push('```json', JSON.stringify(ex.cues), '```', '');
    }
  }
}
writeFileSync(out, lines.join('\n'));
console.log('wrote', out);
